export const seedAdmin = {
  email: 'admin@senordelastintas.com',
  password: 'Admin@123456',
  full_name: 'Administrador Principal',
};

export const seedSecretarias = [
  {
    email: 'secretaria.sucre@senordelastintas.com',
    password: 'Secretaria@123',
    full_name: 'Secretaria Sucre',
  },
  {
    email: 'secretaria.scz@senordelastintas.com',
    password: 'Secretaria@123',
    full_name: 'Secretaria Santa Cruz',
  },
];

export const seedBranches = [
  {
    name: 'Sucursal Sucre',
    address: 'Calle Bolívar #123, Sucre',
    opening_hours: 'Lun-Vie: 8:00-19:00, Sáb: 9:00-17:00',
    location_link: 'https://maps.google.com/?q=-19.0333,-65.2627',
  },
  {
    name: 'Sucursal Santa Cruz',
    address: 'Av. San Martín #456, Santa Cruz',
    opening_hours: 'Lun-Vie: 8:00-20:00, Sáb: 9:00-18:00',
    location_link: 'https://maps.google.com/?q=-17.7833,-63.1821',
  },
];

/** Inventario agosto — catálogo extraído de inventario para aplicacion agosto.pdf
 *  sale_price = valor del PDF (redondeado a 2 decimales). Ítems sin cifra = 0.
 *  El stock físico no venía en el PDF: current_quantity queda en 0.
 */
export const seedSupplies = [
  { code: "ST-0001", name: "TRANSISTORES EPSON A2098&C6082", category: "Electrónica", unit_of_measure: "unidades", sale_price: 108.73, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "TRANSISTORES EPSON A2098&C6082" },
  { code: "ST-0002", name: "TRANSISTORES EPSON A2169&C6017", category: "Electrónica", unit_of_measure: "unidades", sale_price: 97.88, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "TRANSISTORES EPSON A2169&C6017" },
  { code: "ST-0003", name: "TRANSISTORES EPSON A2210&C6082", category: "Electrónica", unit_of_measure: "unidades", sale_price: 94.63, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "TRANSISTORES EPSON A2210&C6082" },
  { code: "ST-0004", name: "TRANSISTORES EPSON A222&6144", category: "Electrónica", unit_of_measure: "unidades", sale_price: 76.80, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "TRANSISTORES EPSON A222&6144" },
  { code: "ST-0005", name: "BOMBA DE TINTA EPSON L3110", category: "Bombas", unit_of_measure: "unidades", sale_price: 495.55, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "BOMBA DE TINTA EPSON L3110" },
  { code: "ST-0006", name: "BOMBA DE TINTA EPSON L14150", category: "Bombas", unit_of_measure: "unidades", sale_price: 728.83, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "BOMBA DE TINTA EPSON L14150" },
  { code: "ST-0007", name: "BOMBA DE TINTA EPSON WF5710", category: "Bombas", unit_of_measure: "unidades", sale_price: 130.45, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "BOMBA DE TINTA EPSON WF5710" },
  { code: "ST-0008", name: "CABLE CABEZAL L220", category: "Repuestos", unit_of_measure: "unidades", sale_price: 50.23, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABLE CABEZAL L220" },
  { code: "ST-0009", name: "CABEZAL CANON TS 9020", category: "Cabezales", unit_of_measure: "unidades", sale_price: 50.23, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "CABEZAL CANON TS 9020" },
  { code: "ST-0010", name: "CABEZAL Epson TM-T20II", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL Epson TM-T20II" },
  { code: "ST-0011", name: "CABEZAL Epson TM-T20IIIL", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL Epson TM-T20IIIL" },
  { code: "ST-0012", name: "CABEZAL Epson TM-T88V", category: "Cabezales", unit_of_measure: "unidades", sale_price: 49.90, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL Epson TM-T88V" },
  { code: "ST-0013", name: "CABEZAL HP951", category: "Cabezales", unit_of_measure: "unidades", sale_price: 49.79, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CABEZAL HP951" },
  { code: "ST-0014", name: "CABEZAL EPSON L1300", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL EPSON L1300" },
  { code: "ST-0015", name: "CABEZAL EPSON L1800", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL EPSON L1800" },
  { code: "ST-0016", name: "CABEZAL EPSON L5590", category: "Cabezales", unit_of_measure: "unidades", sale_price: 434.51, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL EPSON L5590" },
  { code: "ST-0017", name: "CABEZAL L606", category: "Cabezales", unit_of_measure: "unidades", sale_price: 173.33, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL L606" },
  { code: "ST-0018", name: "CABEZAL L8180", category: "Cabezales", unit_of_measure: "unidades", sale_price: 135.45, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL L8180" },
  { code: "ST-0019", name: "CABEZAL WF5710", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CABEZAL WF5710" },
  { code: "ST-0020", name: "CABEZAL M100", category: "Cabezales", unit_of_measure: "unidades", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "CABEZAL M100" },
  { code: "ST-0021", name: "CABEZAL PM", category: "Cabezales", unit_of_measure: "unidades", sale_price: 225.00, brand: "Genérico", umbral_min: 2, commercial_description: "CABEZAL PM" },
  { code: "ST-0022", name: "CABEZAL WF", category: "Cabezales", unit_of_measure: "unidades", sale_price: 2750.00, brand: "Genérico", umbral_min: 2, commercial_description: "CABEZAL WF" },
  { code: "ST-0023", name: "caja reset brother j6720", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 0.00, brand: "Brother", umbral_min: 2, compatibility: "Brother", commercial_description: "caja reset brother j6720" },
  { code: "ST-0024", name: "CAJA RESET EPSONC9344", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CAJA RESET EPSONC9344" },
  { code: "ST-0025", name: "CAJA RESET EPSONC9345", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CAJA RESET EPSONC9345" },
  { code: "ST-0026", name: "caja reset epson CANON G02", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 410.15, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "caja reset epson CANON G02" },
  { code: "ST-0027", name: "caja reset epson f170", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 420.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset epson f170" },
  { code: "ST-0028", name: "caja reset EPSON F570", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 52.36, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset EPSON F570" },
  { code: "ST-0029", name: "caja reset epson t04d1", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 52.36, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset epson t04d1" },
  { code: "ST-0030", name: "caja reset epson T3170", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset epson T3170" },
  { code: "ST-0031", name: "caja reset epson T6712", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset epson T6712" },
  { code: "ST-0032", name: "caja reset epson T6714 WF 878R", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 132.29, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "caja reset epson T6714 WF 878R" },
  { code: "ST-0033", name: "CAJA RESET G3170", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 399.25, brand: "Genérico", umbral_min: 2, commercial_description: "CAJA RESET G3170" },
  { code: "ST-0034", name: "CAJA RESET WF 5810", category: "Cajas reset", unit_of_measure: "unidades", sale_price: 703.90, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CAJA RESET WF 5810" },
  { code: "ST-0035", name: "IMPRESORA CANON IX6810", category: "Impresoras", unit_of_measure: "unidades", sale_price: 414.82, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "IMPRESORA CANON IX6810" },
  { code: "ST-0036", name: "CARTUCHOS CANON 210", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 414.82, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "CARTUCHOS CANON 210" },
  { code: "ST-0037", name: "CARTUCHOS CANON COLOR 211", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 414.82, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "CARTUCHOS CANON COLOR 211" },
  { code: "ST-0038", name: "cartuchos recargable brother j6720", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 2034.56, brand: "Brother", umbral_min: 2, compatibility: "Brother", commercial_description: "cartuchos recargable brother j6720" },
  { code: "ST-0039", name: "cartuchos recargable hp 72", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 205.80, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "cartuchos recargable hp 72" },
  { code: "ST-0040", name: "cartuchos RECARGABLES EPSON T05A WF 869R", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 199.51, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "cartuchos RECARGABLES EPSON T05A WF 869R" },
  { code: "ST-0041", name: "CARTUCHOS RECARGABLES EPSON T5470", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 47.40, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CARTUCHOS RECARGABLES EPSON T5470" },
  { code: "ST-0042", name: "CARTUCHOS RECARGABLES EPSON T5475", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 72.98, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CARTUCHOS RECARGABLES EPSON T5475" },
  { code: "ST-0043", name: "CARTUCHOS RECARGABLES EPSON WF5710,5790,579R,5810,5890,5891", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 69.66, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CARTUCHOS RECARGABLES EPSON WF5710,5790,579R,5810,5890,5891" },
  { code: "ST-0044", name: "CARTUCHOS RECARGABLES EPSON WF 6590", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 50.05, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CARTUCHOS RECARGABLES EPSON WF 6590" },
  { code: "ST-0045", name: "CARTUCHOS recargables pm 225", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 31.14, brand: "Genérico", umbral_min: 2, commercial_description: "CARTUCHOS recargables pm 225" },
  { code: "ST-0046", name: "CARTUCHOS RECARGABLES EPSON T3170,5170", category: "Cartuchos", unit_of_measure: "unidades", sale_price: 46.23, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CARTUCHOS RECARGABLES EPSON T3170,5170" },
  { code: "ST-0047", name: "CHIP BROTHER L103 BK", category: "Chips", unit_of_measure: "unidades", sale_price: 735.77, brand: "Brother", umbral_min: 2, compatibility: "Brother", commercial_description: "CHIP BROTHER L103 BK" },
  { code: "ST-0048", name: "CHIP BROTHER L103 CY", category: "Chips", unit_of_measure: "unidades", sale_price: 3144.77, brand: "Brother", umbral_min: 2, compatibility: "Brother", commercial_description: "CHIP BROTHER L103 CY" },
  { code: "ST-0049", name: "CHIP BROTHER L103 MAG", category: "Chips", unit_of_measure: "unidades", sale_price: 814.90, brand: "Brother", umbral_min: 2, compatibility: "Brother", commercial_description: "CHIP BROTHER L103 MAG" },
  { code: "ST-0050", name: "CHIP CANON 2630", category: "Chips", unit_of_measure: "unidades", sale_price: 889.08, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "CHIP CANON 2630" },
  { code: "ST-0051", name: "CHIP CANON G2160", category: "Chips", unit_of_measure: "unidades", sale_price: 1000.36, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "CHIP CANON G2160" },
  { code: "ST-0052", name: "chip epson C9344", category: "Chips", unit_of_measure: "unidades", sale_price: 1190.13, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "chip epson C9344" },
  { code: "ST-0053", name: "chip epson C9345", category: "Chips", unit_of_measure: "unidades", sale_price: 2637.77, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "chip epson C9345" },
  { code: "ST-0054", name: "chip epson t376", category: "Chips", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "chip epson t376" },
  { code: "ST-0055", name: "chip epson T6712", category: "Chips", unit_of_measure: "unidades", sale_price: 62.17, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "chip epson T6712" },
  { code: "ST-0056", name: "CHIP HP 7740 MAG", category: "Chips", unit_of_measure: "unidades", sale_price: 62.17, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP 7740 MAG" },
  { code: "ST-0057", name: "CHIP HP 7740 BK", category: "Chips", unit_of_measure: "unidades", sale_price: 55.99, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP 7740 BK" },
  { code: "ST-0058", name: "CHIP HP 7740 M", category: "Chips", unit_of_measure: "unidades", sale_price: 27.06, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP 7740 M" },
  { code: "ST-0059", name: "CHIP HP 7740 Y", category: "Chips", unit_of_measure: "unidades", sale_price: 14.18, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP 7740 Y" },
  { code: "ST-0060", name: "CHIP HP712 YELLOW", category: "Chips", unit_of_measure: "unidades", sale_price: 136.49, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP712 YELLOW" },
  { code: "ST-0061", name: "CHIP HP712BK", category: "Chips", unit_of_measure: "unidades", sale_price: 136.49, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP712BK" },
  { code: "ST-0062", name: "CHIP HP728 MBK", category: "Chips", unit_of_measure: "unidades", sale_price: 136.49, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP HP728 MBK" },
  { code: "ST-0063", name: "chip hp728xl c", category: "Chips", unit_of_measure: "unidades", sale_price: 1112.35, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "chip hp728xl c" },
  { code: "ST-0064", name: "chip hp728xl m", category: "Chips", unit_of_measure: "unidades", sale_price: 2479.20, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "chip hp728xl m" },
  { code: "ST-0065", name: "chip hp728xl y", category: "Chips", unit_of_measure: "unidades", sale_price: 3507.36, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "chip hp728xl y" },
  { code: "ST-0066", name: "CHIP INICIO HP DESIGNJET T650", category: "Chips", unit_of_measure: "unidades", sale_price: 362.40, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CHIP INICIO HP DESIGNJET T650" },
  { code: "ST-0067", name: "chip SC13MB", category: "Chips", unit_of_measure: "unidades", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "chip SC13MB" },
  { code: "ST-0068", name: "chip SC23MB", category: "Chips", unit_of_measure: "unidades", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "chip SC23MB" },
  { code: "ST-0069", name: "CHIP T04D1/EWMB1", category: "Chips", unit_of_measure: "unidades", sale_price: 414.08, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T04D1/EWMB1" },
  { code: "ST-0070", name: "CHIP T3180 bk", category: "Chips", unit_of_measure: "unidades", sale_price: 414.08, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T3180 bk" },
  { code: "ST-0071", name: "CHIP T3180 CY", category: "Chips", unit_of_measure: "unidades", sale_price: 386.38, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T3180 CY" },
  { code: "ST-0072", name: "CHIP T3180 M", category: "Chips", unit_of_measure: "unidades", sale_price: 376.08, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T3180 M" },
  { code: "ST-0073", name: "CHIP T3180 Y", category: "Chips", unit_of_measure: "unidades", sale_price: 485.56, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T3180 Y" },
  { code: "ST-0074", name: "CHIP T6716", category: "Chips", unit_of_measure: "unidades", sale_price: 125.36, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T6716" },
  { code: "ST-0075", name: "CHIP T6997", category: "Chips", unit_of_measure: "unidades", sale_price: 114.55, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP T6997" },
  { code: "ST-0076", name: "chip t9071xl bk", category: "Chips", unit_of_measure: "unidades", sale_price: 499.99, brand: "Genérico", umbral_min: 2, commercial_description: "chip t9071xl bk" },
  { code: "ST-0077", name: "chip t9072xl y", category: "Chips", unit_of_measure: "unidades", sale_price: 499.99, brand: "Genérico", umbral_min: 2, commercial_description: "chip t9072xl y" },
  { code: "ST-0078", name: "chip t9074xl c", category: "Chips", unit_of_measure: "unidades", sale_price: 475.68, brand: "Genérico", umbral_min: 2, commercial_description: "chip t9074xl c" },
  { code: "ST-0079", name: "chip t9073 xl M", category: "Chips", unit_of_measure: "unidades", sale_price: 502.28, brand: "Genérico", umbral_min: 2, commercial_description: "chip t9073 xl M" },
  { code: "ST-0080", name: "CISS EPSON T3170 CON CADENILLA", category: "CISS", unit_of_measure: "unidades", sale_price: 55.96, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CISS EPSON T3170 CON CADENILLA" },
  { code: "ST-0081", name: "ciss epson t50", category: "CISS", unit_of_measure: "unidades", sale_price: 55.96, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "ciss epson t50" },
  { code: "ST-0082", name: "CISS EPSON WF2950", category: "CISS", unit_of_measure: "unidades", sale_price: 55.96, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CISS EPSON WF2950" },
  { code: "ST-0083", name: "CISS HP 9730", category: "CISS", unit_of_measure: "unidades", sale_price: 54.25, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "CISS HP 9730" },
  { code: "ST-0084", name: "CISS TX212", category: "CISS", unit_of_measure: "unidades", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "CISS TX212" },
  { code: "ST-0085", name: "COATING EPSON WF", category: "Repuestos", unit_of_measure: "unidades", sale_price: 6590.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "COATING EPSON WF" },
  { code: "ST-0086", name: "CORREA DE CABEZAL WF5710", category: "Repuestos", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CORREA DE CABEZAL WF5710" },
  { code: "ST-0087", name: "CORREA L14150", category: "Repuestos", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CORREA L14150" },
  { code: "ST-0088", name: "CORREA WF", category: "Repuestos", unit_of_measure: "unidades", sale_price: 2870.00, brand: "Genérico", umbral_min: 2, commercial_description: "CORREA WF" },
  { code: "ST-0089", name: "CORTADORA TM T88V", category: "Repuestos", unit_of_measure: "unidades", sale_price: 68.84, brand: "Genérico", umbral_min: 2, commercial_description: "CORTADORA TM T88V" },
  { code: "ST-0090", name: "CUTTER Epson TM-T88V", category: "Repuestos", unit_of_measure: "unidades", sale_price: 500.85, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CUTTER Epson TM-T88V" },
  { code: "ST-0091", name: "CUTTER Epson TM-T88V (2)", category: "Repuestos", unit_of_measure: "unidades", sale_price: 528.45, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CUTTER Epson TM-T88V (2)" },
  { code: "ST-0092", name: "CUTTER Epson TM-T88V (3)", category: "Repuestos", unit_of_measure: "unidades", sale_price: 556.04, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "CUTTER Epson TM-T88V (3)" },
  { code: "ST-0093", name: "DECODIFICADOR HPT610", category: "Repuestos", unit_of_measure: "unidades", sale_price: 500.61, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "DECODIFICADOR HPT610" },
  { code: "ST-0094", name: "CHIP E09A7418A", category: "Chips", unit_of_measure: "unidades", sale_price: 788.50, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP E09A7418A" },
  { code: "ST-0095", name: "CHIP E09A88GA", category: "Chips", unit_of_measure: "unidades", sale_price: 1595.96, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP E09A88GA" },
  { code: "ST-0096", name: "CHIP E09A92GA", category: "Chips", unit_of_measure: "unidades", sale_price: 3571.20, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP E09A92GA" },
  { code: "ST-0097", name: "ESPONJA L8050", category: "Repuestos", unit_of_measure: "unidades", sale_price: 174.84, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "ESPONJA L8050" },
  { code: "ST-0098", name: "ESPONJAS L5590", category: "Repuestos", unit_of_measure: "unidades", sale_price: 8028.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "ESPONJAS L5590" },
  { code: "ST-0099", name: "ESPONJAS T04D1", category: "Repuestos", unit_of_measure: "unidades", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "ESPONJAS T04D1" },
  { code: "ST-0100", name: "ESPONJAS L3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "ESPONJAS L3110" },
  { code: "ST-0101", name: "ESPONJAS WF 5710", category: "Repuestos", unit_of_measure: "unidades", sale_price: 437.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "ESPONJAS WF 5710" },
  { code: "ST-0102", name: "FUSIBLE F1 L220", category: "Repuestos", unit_of_measure: "unidades", sale_price: 65.10, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "FUSIBLE F1 L220" },
  { code: "ST-0103", name: "FILMINA HP1102W", category: "Repuestos", unit_of_measure: "unidades", sale_price: 65.10, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "FILMINA HP1102W" },
  { code: "ST-0104", name: "FILMINA HP1020", category: "Repuestos", unit_of_measure: "unidades", sale_price: 82.60, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "FILMINA HP1020" },
  { code: "ST-0105", name: "FLEX EPSON L3110 PORTACABEZAL", category: "Repuestos", unit_of_measure: "unidades", sale_price: 470.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "FLEX EPSON L3110 PORTACABEZAL" },
  { code: "ST-0106", name: "FLEX SENSOR CABEZAL L3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 0.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "FLEX SENSOR CABEZAL L3110" },
  { code: "ST-0107", name: "TRANSISTORES EPSON FTD01N&FTD02P", category: "Electrónica", unit_of_measure: "unidades", sale_price: 842.25, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "TRANSISTORES EPSON FTD01N&FTD02P" },
  { code: "ST-0108", name: "FUENTE L220", category: "Repuestos", unit_of_measure: "unidades", sale_price: 1590.62, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "FUENTE L220" },
  { code: "ST-0109", name: "FUENTE L 3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 510.19, brand: "Genérico", umbral_min: 2, commercial_description: "FUENTE L 3110" },
  { code: "ST-0110", name: "Gear L3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 176.50, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "Gear L3110" },
  { code: "ST-0111", name: "generador de ozono", category: "Equipos", unit_of_measure: "unidades", sale_price: 154.75, brand: "Genérico", umbral_min: 2, commercial_description: "generador de ozono" },
  { code: "ST-0112", name: "GOMAS DE ARRASTRE EPSON L220", category: "Repuestos", unit_of_measure: "unidades", sale_price: 173.25, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "GOMAS DE ARRASTRE EPSON L220" },
  { code: "ST-0113", name: "GOMAS DE ARRASTRE EPSON WF 5710", category: "Repuestos", unit_of_measure: "unidades", sale_price: 232.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "GOMAS DE ARRASTRE EPSON WF 5710" },
  { code: "ST-0114", name: "GOMAS ARRASTRE EPSON L3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 413.35, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "GOMAS ARRASTRE EPSON L3110" },
  { code: "ST-0115", name: "GOMAS ARRASTRE EPSON L6171", category: "Repuestos", unit_of_measure: "unidades", sale_price: 142.34, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "GOMAS ARRASTRE EPSON L6171" },
  { code: "ST-0116", name: "FLEX CABEZAL L3110", category: "Repuestos", unit_of_measure: "unidades", sale_price: 3920.40, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "FLEX CABEZAL L3110" },
  { code: "ST-0117", name: "SUCCIONADOR HP 72", category: "Repuestos", unit_of_measure: "unidades", sale_price: 350.19, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "SUCCIONADOR HP 72" },
  { code: "ST-0118", name: "SUCCIONADOR HP 954", category: "Repuestos", unit_of_measure: "unidades", sale_price: 350.19, brand: "HP", umbral_min: 2, compatibility: "HP", commercial_description: "SUCCIONADOR HP 954" },
  { code: "ST-0119", name: "CHIP IC A222/6144", category: "Chips", unit_of_measure: "unidades", sale_price: 436.90, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP IC A222/6144" },
  { code: "ST-0120", name: "CHIP IC E09A92GA", category: "Chips", unit_of_measure: "unidades", sale_price: 218.35, brand: "Genérico", umbral_min: 2, commercial_description: "CHIP IC E09A92GA" },
  { code: "ST-0121", name: "Ink Damper", category: "Repuestos", unit_of_measure: "unidades", sale_price: 388.58, brand: "Genérico", umbral_min: 2, commercial_description: "Ink Damper" },
  { code: "ST-0122", name: "KIT 544 4 COLORES", category: "Kits", unit_of_measure: "unidades", sale_price: 49.04, brand: "Genérico", umbral_min: 2, commercial_description: "KIT 544 4 COLORES" },
  { code: "ST-0123", name: "LITRO CYAN FOTO", category: "Tintas", unit_of_measure: "litros", sale_price: 426.00, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO CYAN FOTO" },
  { code: "ST-0124", name: "LITRO CYAN UV", category: "Tintas", unit_of_measure: "litros", sale_price: 426.00, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO CYAN UV" },
  { code: "ST-0125", name: "LITRO GRAY EPSON", category: "Tintas", unit_of_measure: "litros", sale_price: 426.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "LITRO GRAY EPSON" },
  { code: "ST-0126", name: "LITRO INKCORE WF5710 BK", category: "Tintas", unit_of_measure: "litros", sale_price: 59.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "LITRO INKCORE WF5710 BK" },
  { code: "ST-0127", name: "LITRO INKCORE WF5710 CY", category: "Tintas", unit_of_measure: "litros", sale_price: 59.60, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "LITRO INKCORE WF5710 CY" },
  { code: "ST-0128", name: "LITRO INKCORE WF5710 MAGENTA", category: "Tintas", unit_of_measure: "litros", sale_price: 496.00, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "LITRO INKCORE WF5710 MAGENTA" },
  { code: "ST-0129", name: "LITRO INKCORE WF5710 YELLOW", category: "Tintas", unit_of_measure: "litros", sale_price: 678.50, brand: "Epson", umbral_min: 2, compatibility: "Epson", commercial_description: "LITRO INKCORE WF5710 YELLOW" },
  { code: "ST-0130", name: "LITRO LIMPIACABEZAL", category: "Químicos", unit_of_measure: "litros", sale_price: 867.00, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO LIMPIACABEZAL" },
  { code: "ST-0131", name: "LITRO TINTA MAGENTA FOTO", category: "Tintas", unit_of_measure: "litros", sale_price: 80.78, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA MAGENTA FOTO" },
  { code: "ST-0132", name: "LITRO TINTA MAGENTA UV", category: "Tintas", unit_of_measure: "litros", sale_price: 200.85, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA MAGENTA UV" },
  { code: "ST-0133", name: "LITRO TINTA NEGRO FOTO CANON", category: "Tintas", unit_of_measure: "litros", sale_price: 678.00, brand: "Canon", umbral_min: 2, compatibility: "Canon", commercial_description: "LITRO TINTA NEGRO FOTO CANON" },
  { code: "ST-0134", name: "LITRO TINTA NEGRO UV", category: "Tintas", unit_of_measure: "litros", sale_price: 1300.30, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA NEGRO UV" },
  { code: "ST-0135", name: "LITRO TINTA UV CYAN", category: "Tintas", unit_of_measure: "litros", sale_price: 70.43, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA UV CYAN" },
  { code: "ST-0136", name: "LITRO TINTA UV MAGENTA", category: "Tintas", unit_of_measure: "litros", sale_price: 0.00, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA UV MAGENTA" },
  { code: "ST-0137", name: "LITRO TINTA UV NEGRO", category: "Tintas", unit_of_measure: "litros", sale_price: 601.80, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA UV NEGRO" },
  { code: "ST-0138", name: "LITRO TINTA UV YELLOW", category: "Tintas", unit_of_measure: "litros", sale_price: 436.70, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO TINTA UV YELLOW" },
  { code: "ST-0139", name: "LITRO YELLOW FOTO", category: "Tintas", unit_of_measure: "litros", sale_price: 69.16, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO YELLOW FOTO" },
  { code: "ST-0140", name: "LITRO YELLOW UV", category: "Tintas", unit_of_measure: "litros", sale_price: 69.16, brand: "Genérico", umbral_min: 2, commercial_description: "LITRO YELLOW UV" },
];

export const seedEmployees = [
  { full_name: 'Juan Pérez', access_pin: 'Pin@1234', position: 'Vendedor' },
  { full_name: 'María González', access_pin: 'Pin@5678', position: 'Cajera' },
  { full_name: 'Carlos López', access_pin: 'Pin@9012', position: 'Técnico' },
];

export const seedInventoryDefaults = {
  current_quantity: 0,
  minimum_stock: 2,
};
